name: fanfou

# 北京时间周一至周五下午四点执行
on:
  schedule:
#  - cron: "0 8 * * 1-5"
  - cron: "1 * * * *"

# 通知
jobs:
  # 包含一个通知任务
  notification:
    # 使用最新 ubuntu 系统
    runs-on: ubuntu-latest

    # 具体步骤
    steps:

    # 发送通知
    - name: send notification
      env:
        URL: ${{ secrets.TEHANG_SHENGHUO_ROBOT_WEBHOOK }}
      uses: wei/curl@v1
      with:
        args: -X POST $URL 
#        args: $URL -H "Content-Type: application/json" -d '{"msgtype": "text", "text": {"content": "一分钟一次消息-来自阿狼"}}'
        # args: www.baidu.com -H 'Content-Type: application/json' -d '{}'
         

