name: fanfou

# 北京时间周一至周五下午四点执行
on:
  push:
    branches: [ master ]
  schedule:
#  - cron: "0 8 * * 1-5"
  - cron: "*/60 * * * *"

# 通知
jobs:
  # 包含一个通知任务
  notification:
    # 使用最新 ubuntu 系统
    runs-on: ubuntu-latest

    # 具体步骤
    steps:

    # 发送通知
    - name: send notification
      env:
        URL: ${{ secrets.TEHANG_SHENGHUO_ROBOT_WEBHOOK }}
      run: |
        curl --request POST \
        --url $URL \
        --header 'content-type: application/json' \
        --data-binary '@.github/workflows/fanfou-content.text'
