name: fanfou

# 北京时间周一至周五下午四点执行
on:
  push:
    branches: [ master ]
  schedule:
#  - cron: "0 8 * * 1-5"
  - cron: "*/60 * * * *"

# 通知
jobs:
  # 包含一个通知任务
  notification:
    # 使用最新 ubuntu 系统
    runs-on: ubuntu-latest

    # 具体步骤
    steps:

    # 发送通知
    - name: send notification
      env:
        URL: ${{ secrets.TEHANG_SHENGHUO_ROBOT_WEBHOOK }}
      run: |
        curl --request POST \
        --url $URL \
        --header 'content-type: application/json' \
        --data '{
          "msgtype":"text",
          "mentioned_list":["@all"],
          "text":{"content":"今日晚餐推荐：一。盒马经典🦛套餐\n1 红烧乳鸽+酸奶\n2 烧鸭拼叉烧饭\n3 酸菜巴沙鱼+米饭\n4 辣椒小炒肉+米饭\n5 秘制咖喱鸡块饭\n6 澳洲肥牛烤肉饭\n7 菜花炒猪颈肉+米饭\n8 招牌澳洲肥牛饭\n9 经典黑椒牛肉炒饭\n10 虾三鲜肉水饺\n二。三七减脂🥗餐厅\n11 鸡胸沙拉+果汁\n12 彩虹素食沙拉+果汁\n13 越南春卷+蜂蜜薄荷水\n14 香煎鸡胸意面+小沙拉\n三。车前外带🍣寿司\n15 海底总动员套餐\n16 鱼虾联盟套餐\n四。罗阿玛🍜螺蛳粉\n17 墨鱼丸螺蛳粉套餐\n18 港式烧鸭螺蛳粉+卤蛋+豆泡\n19 招牌原味螺蛳粉+卤蛋+豆泡\n五。永和🌮大王\n20 卤肉饭拼宫保鸡丁蒸蛋/特惠套餐\n21 黑椒牛柳拼宫保鸡丁套餐\n22 小撕鸡卤肉饭椰果冰饮套餐\n六。老郑家东北春饼\n23 超值招牌春饼套餐\n24 家鸡焖土豆+米饭+爽口小菜\n25 酸菜猪肉水饺+小米粥+爽口小菜。5点30 发车，自点小伙伴记得找我报销餐费"}
          }'

