name: yufou

# 北京时间周四、周五下午5点40执行
on:
#  push:
#    branches: [ master ]
  schedule:
  - cron: "0 9 * * 4-5"
#  - cron: "*/60 * * * *"

# 通知
jobs:
  # 包含一个通知任务
  notification:
    # 使用最新 ubuntu 系统
    runs-on: ubuntu-latest

    # 具体步骤
    steps:

    # 发送通知
    - name: send notification
      env:
        URL: ${{ secrets.TEHANG_YUMAOQIU_ROBOT_WEBHOOK }}
      run: |
        curl --request POST \
        --url $URL \
        --header 'content-type: application/json' \
        --data '{
          "msgtype":"text",
          "text":{
              "mentioned_mobile_list":["@all"],
              "content":"本周五晚 18:00-20:00 龙珠羽毛球馆预定场地一个，欢迎参与。"
              }
          }'
